version: '3.9'

services:

  backend:
    build: .

    ports:
      - "8000:8000"

    volumes:
      - .:/app

    depends_on:
      - postgres

    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/docdb

  postgres:
    image: postgres:15

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: docdb

    ports:
      - "5432:5432"